name: Formulario Code Aplication

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Instalar Bibliotecas necessárias
      run: pip install pyinstaller
    - name: Criar Executavel 2.0 do Formulario
      run: pyinstaller --onefile FormularioAppV2.0.py
