name: Formulario Code Aplication

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Criar Executavel 2.0 do Formulario
      run: |
        python FormularioAppV2.0.py
